### ISSUE TITLE
const declarations should allow casting

### ISSUE THREAD

**Issue by rbenua** [moroso/compiler#55]
When trying to define a constant pointer: `const uart_base: *u32 = 0x80001000 as *u32;`
I get the following error: `Non-constant expression where constant expected`.
This should be possible, as otherwise there's no way to initialize an arbitrary constant pointer.

**Comment by mrwright** [comment]
Resolved by https://github.com/moroso/compiler/commit/fd9fd318f99401f77c05cc92b83e1a91fda1ca53
